### PR TITLE
Wtg 44 upgrade to the latest bootstrap

### PR DESCRIPTION
**Pull request by Drillllll**
updated bootstrap to v5, fixed all the problems with the layout after the update. Updating bootstrap will allow for using cards, inputs modals, snackbards and more in the future 

Also added font awesome for icons (glyphicons are outdated in new bootstrap)
new icons to choose from:

https://fontawesome.com/v4/icons/

### CODE REVIEW

**Comment by Kondziow** [comment]
image
I think image should be in the center

**Comment by Kondziow** [comment]
image
Clicking in this field, in 'your routes' results in redirection to the 'routes' URL
image
And you cant edit your route (you should be able to)

**Comment by Kondziow** [comment]
Adding new icons is another task?

**Review by Kondziow — CHANGES_REQUESTED** [review]
Comments above

**Comment by Drillllll** [comment]
@Kondziow brother forgot to do npm install

**Comment by Kondziow** [comment]
Ok, now works

But 
image
The route items don't have full border

**Comment by Drillllll** [comment]
Let me know if my changes fixed the layout problems (mainly font size). Small layout problems such as lack of border, button spacing and so on can be solved in another layout tasks if they don't make it hard to use the app.

**Review by Kondziow — APPROVED** [review]

**Comment by Kondziow** [comment]
Okay, now it looks good, despite lack of border and that redirection I have mentioned above

**Review by Janek1010 — APPROVED** [review]

**Pull request merged**
